name: Build Extension

on:
  workflow_dispatch:
    inputs:
      build-targets:
        description: 'Select build targets'
        required: true
        type: choice
        options:
          - windows-x64
          - windows-arm64
          - linux-x64
          - linux-arm64
          - linux-armhf
          - alpine-x64
          - darwin-x64
          - darwin-arm64

jobs:
  build:
    runs-on: ${{ contains(github.event.inputs.build-targets, 'windows') && 'windows-latest' || contains(github.event.inputs.build-targets, 'darwin') && 'macos-latest' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: win32
            arch: x64
            target: windows-x64
          - platform: win32
            arch: arm64
            target: windows-arm64
          - platform: linux
            arch: x64
            target: linux-x64
          - platform: linux
            arch: arm64
            target: linux-arm64
          - platform: linux
            arch: armhf
            target: linux-armhf
          - platform: alpine
            arch: x64
            target: alpine-x64
          - platform: darwin
            arch: x64
            target: darwin-x64
          - platform: darwin
            arch: arm64
            target: darwin-arm64
    if: contains(github.event.inputs.build-targets, matrix.target)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install core dependencies
        run: |
          cd ${{ github.workspace }}/core
          npm ci

      - name: Install extension dependencies
        run: |
          cd ${{ github.workspace }}/extensions/vscode
          npm ci

      - name: Prepackage the extension
        run: |
          cd ${{ github.workspace }}/extensions/vscode
          npm run prepackage -- --target ${{ matrix.platform }}-${{ matrix.arch }}

      - name: Re-install esbuild
        run: |
          cd extensions/vscode
          npm install -f esbuild

      - name: Package the extension
        run: |
          cd extensions/vscode
          npx vsce package --no-dependencies --target ${{ matrix.platform }}-${{ matrix.arch }}

      - name: Upload .vsix artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-vsix
          path: extensions/vscode/*.vsix
